server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: aop-demo

  # 日志配置
  logging:
    level:
      com.example.aop: DEBUG
      org.springframework.aop: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# AOP配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

